username="id:shub79"
password="id:pass"
company="name:company"
mobile="name:mobile number"
country="xpath://label[text()='Country']//input"
btn="xpath://button[@value='Submit']"
first_crush="id:inp_val"
firstname="xpath://input[@placeholder='First Enter name']"
lastname="xpath://input[@placeholder='Enter Last name']"
link="xpath://div[@class='dropdown-content']//a[text()='Join Training']"
card_dropdown="id:cars"
date="xpath://input[@name='the_date']"
table="xpath://table[@class='table hover']//tbody//tr//td"
file="id:myFile"
alert1="xpath://button[@onclick='windowAlertFunction()']"
alert_2="xpath://button[@onclick='promptAlertFunction()']"
openbtn="id:myBtn"
search_btn="id:dt-search-0"
filter="xpath://tbody[@class='row-striping row-hover']//tr//td"